# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 05:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0002_auto_20161227_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d')),
                ('blogpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogger.BlogPost')),
            ],
        ),
    ]
