# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0004_blogpostcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_banner',
            field=models.ImageField(null=True, upload_to='images/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_description',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
