# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0005_auto_20170101_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_background_color',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
